apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: aro-clusters-gitops
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterSets:
    - aro-clusters
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - primary-cluster
                - secondary-cluster
