apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: busybox-drpc
  namespace: openshift-gitops
  labels:
    app: busybox-sample
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  preferredCluster: primary-cluster
  failoverCluster: secondary-cluster
  drPolicyRef:
    name: drpolicy
  placementRef:
    kind: Placement
    name: busybox-placement
    namespace: openshift-gitops
  pvcSelector:
    matchLabels:
      appname: busybox
