apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: aro-clusters
  namespace: busybox-sample
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterSet: aro-clusters
