applications:

  acm-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: open-cluster-management
    source:
      path: clusters/hub/overlays/acm-operator

  acm-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: open-cluster-management
    source:
      path: clusters/hub/overlays/acm-configuration         

  odf-multicluster-orchestrator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '20'
    destination:
      namespace: odf-multicluster-orchestrator
    source:
      path: clusters/hub/overlays/odf-multicluster-orchestrator

  managedclusterset:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '30'
    destination:
      namespace: open-cluster-management
    source:
      path: clusters/hub/overlays/managedclusterset
    ignoreDifferences:
      - group: "cluster.open-cluster-management.io"
        kind: ManagedCluster
        jsonPointers:
          - /metadata/labels/vendor
          - /metadata/labels/cloud

  klusterletaddonconfig:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '40'
    destination:
      namespace: open-cluster-management
    source:
      path: components/klusterletaddonconfig

  submariner:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '50'
    destination:
      namespace: open-cluster-management
    source:
      path: components/submariner