---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../components/managedclusterset/

patches:
  - target:
      kind: ManagedClusterSet
      name: odf-clusters
    patch: |-
      - op: replace
        path: /metadata/name
        value: aro-clusters
  - path: ./patch-managedcluster-primary-cluster.yaml
  - path: ./patch-managedcluster-secondary-cluster.yaml
