apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: obc-sample-writer
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: obc-sample-writer
              requeueAfterSeconds: 30
          - git:
              repoURL: https://github.com/trevorbox/odf.git
              revision: HEAD
              requeueAfterSeconds: 30
              files:
                - path: components/obc-sample/cluster/*.yaml
  template:
    metadata:
      name: obc-sample-writer-{{.name}}
      labels:
        app: obc-sample
    spec:
      project: default
      source:
        repoURL: https://github.com/trevorbox/odf.git
        targetRevision: HEAD
        path: components/obc-sample/workload-writer
        kustomize:
          patches:
            - target:
                kind: Deployment
                name: obc-sample
              patch: |-
                - op: replace
                  path: /spec/template/spec/containers/0/env/0/value
                  value: {{.s3Host | quote}}
      destination:
        server: "{{.server}}"
        namespace: obc-sample
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
