apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - placement-buckets.yaml
  - placement-writer.yaml
  - applicationset-replication.yaml
  - applicationset-bucket.yaml
  - applicationset-writer.yaml
