---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./managedclusterset-odf-clusters.yaml
  - ./managedcluster-primary-cluster.yaml
  - ./managedcluster-secondary-cluster.yaml
