apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: busybox-subscription-placementrule
  namespace: busybox-subscription
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterSelector:
    matchLabels:
      name: primary-cluster
  schedulerName: ramen
