installRequiredPythonLibraries: false
approveManualInstallPlanViaHook: true

installPlanApproverAndVerifyJobsImage: quay.io/trevorbox/installplanapproverandverifier:4.16.0 # quay.io/openshift/origin-cli:4.16

# operatorGroups:
# - name: odf-multicluster-orchestrator
#   createNamespace: true

operators:
- channel: stable-4.20
  installPlanApproval: Manual
  name: odf-multicluster-orchestrator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  csv: odf-multicluster-orchestrator.v4.20.19-rhodf
  namespace: openshift-operators
  installPlanVerifierActiveDeadlineSeconds: 1200
